spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1006751018797-evppuca5pjm19enrla1sgnrq1p7lrc4r.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauthTest
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 4
    url: jdbc:mysql://database-1.cvqiik6wwe2f.ap-northeast-2.rds.amazonaws.com:3306/teams
    username: admin
    password: seoil7345!
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    async:
      request-timeout: -1

jwt:
  secret: NWYyZDU2NGE4MDNmZDNhYzM0MzdhNDU2YzRlNGU0NTI0ZTQ1MjRlNDUyNGU0NTI0ZTQ1MjRlNDUyNGU0NTI0ZQ==
  expiration: 3600000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.transaction: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.seoil.team.controller

server:
  tomcat:
    threads:
      max: 50
      min-spare: 10

cors:
  allowed-origins: [http://192.168.0.26:3090, http://localhost:3000, http://localhost:3090, http://seoil-ict-react.s3-website.ap-northeast-2.amazonaws.com]
  allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
  allowed-headers: ["*"]
  allow-credentials: true
  max-age: 3600


alphavantage:
  api:
    key: ED55TQUTAEGO18HR

openai:
  api:
    key: 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
    url : https://api.openai.com/v1/chat/completions


